[4.1] Обновление до новой версии + новые расширения
JPathRu/localisation pull request #84
Opened 2022-01-22 16:42 UTC by Kostelano

Работа над переводом текущих изменений для 4.1 + новых расширений.

Joomla 4.1 запланирована на 15 февраля.

2022-02-03 14:23 UTC, b2z requested changes

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_DESC="Включить или отключить функцию логирования событий, за&#160;исключением категории устаревшего API."
Что-то тут вкралось `&#160;`
`за&#160;исключением`

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_N_ITEMS_DELETED_2="%d задачи успешно удалено."
%d задачи успешно удален**ы**

И дальше по тексту везде _2 изменить на **ы**

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
"Компонент для управления планировщиком задач."

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/com_scheduler.sys.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
"Компонент для управления планировщиком задач."

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/com_tags.ini
> +COM_TAGS_N_QUICKICON_SRONLY_2="Теги: %d тега опубликовано"
опубликован**ы**

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/plg_task_demotasks.ini
> +PLG_TASK_DEMO_TASKS_SLEEP_TIMEOUT_LABEL="Тайм-аут сна (секунд)"
Я бы писал (секунды)

2022-02-03 14:23 UTC, b2z commented on administrator/language/ru-RU/plg_task_demotasks.ini
> +PLG_TASK_DEMO_TASKS_RESUMABLE_TIMEOUT_LABEL="Тайм-аут на шаг (секунд)"
Я бы писал (секунды)

2022-02-03 14:27 UTC, b2z commented
@Kostelano в plg_user_token отсутствует перевод

`PLG_USER_TOKEN_TOKEN_DESC="This is your token. Use it in third party applications requiring remote access to your site through the Joomla API application."`
Предлагаю такой перевод
`Это ваш токен. Используйте его в сторонних приложениях, требующих удаленного доступа к вашему сайту через приложение Joomla API.`

2022-02-03 14:47 UTC, Kostelano commented on administrator/language/ru-RU/plg_task_demotasks.ini
> +PLG_TASK_DEMO_TASKS_SLEEP_TIMEOUT_LABEL="Тайм-аут сна (секунд)"
В других строках локализации мы используем **X (минут)**, **X (часов)**, **X (дней)**. Я бы предпочел не менять на "секунды", иначе есть смысл менять везде :)

2022-02-03 15:06 UTC, b2z commented on administrator/language/ru-RU/plg_task_demotasks.ini
> +PLG_TASK_DEMO_TASKS_SLEEP_TIMEOUT_LABEL="Тайм-аут сна (секунд)"
Это моё мнение. Я бы писал в именительном падеже. В компоненте что-то я это пропустил.

2022-02-03 16:16 UTC, b2z commented
@Kostelano ты запросил ревью, но не вижу изменений.

2022-02-03 18:00 UTC, Kostelano commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_N_ITEMS_DELETED_2="%d задачи успешно удалено."
Исправлено в https://github.com/JPathRu/localisation/commit/cd08854ddd9c446c44047ee62b134c8067c34ccb

2022-02-03 18:00 UTC, Kostelano commented on administrator/language/ru-RU/com_tags.ini
> +COM_TAGS_N_QUICKICON_SRONLY_2="Теги: %d тега опубликовано"
Исправлено в https://github.com/JPathRu/localisation/commit/cd08854ddd9c446c44047ee62b134c8067c34ccb

2022-02-03 18:01 UTC, Kostelano commented
> В plg_user_token отсутствует перевод
> 
> `PLG_USER_TOKEN_TOKEN_DESC="This is your token. Use it in third party applications requiring remote access to your site through the Joomla API application."` Предлагаю такой перевод `Это ваш токен. Используйте его в сторонних приложениях, требующих удаленного доступа к вашему сайту через приложение Joomla API.`

Упс, пропустил еще при переводе 4.0.
Исправлено в https://github.com/JPathRu/localisation/commit/cd08854ddd9c446c44047ee62b134c8067c34ccb.

2022-02-03 20:58 UTC, b2z commented on administrator/language/ru-RU/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_DESC="Включить или отключить функцию логирования событий, за&#160;исключением категории устаревшего API."
Тут не исправлено

2022-02-04 06:46 UTC, Kostelano commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
Я вот думаю. Компонент является планировщиком задач - он так и называется, и управлять самим собой так себе формулировка. Да и в других компонентах плюс/минус идентичная представленной формулировка.

```
COM_BANNERS_XML_DESCRIPTION="Компонент для управления баннерами и клиентами."
COM_CACHE_XML_DESCRIPTION="Компонент для управления группами кэша."
COM_CATEGORIES_XML_DESCRIPTION="Компонент для управления категориями."
COM_CONTACT_XML_DESCRIPTION="Компонент для управления контактами."
COM_CONTENT_XML_DESCRIPTION="Компонент для управления материалами."
```

И так далее. Что скажешь?

2022-02-04 07:05 UTC, b2z commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
Меня тут беспокоит только то, что Управление задачами не до конца раскрывает, о каких задачах идёт речь. Слишком абстрактно, задачи разные бывают. Что-то пока не могу придумать как лучше обыграть.

2022-02-04 07:46 UTC, Kostelano commented on administrator/language/ru-RU/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_DESC="Включить или отключить функцию логирования событий, за&#160;исключением категории устаревшего API."
https://github.com/JPathRu/localisation/commit/853e11599953daa294ed17c2f7cc130fe529a966

Это не ошибка и не опечатка, а неразрывный пробел. Частицы в/не/на/за и т.д. лучше не переносить на новую строку отдельно от слова. Но т.к. мониторы у всех разные - не угадаешь перенос строки, можно попробовать этим пренебречь.

2022-02-04 07:49 UTC, progreccor commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
планировщик задач нормальный термин. Навряд ли вы найдете что-то лучше

2022-02-04 07:50 UTC, b2z commented on administrator/language/ru-RU/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_DESC="Включить или отключить функцию логирования событий, за&#160;исключением категории устаревшего API."
Ах вот оно что. Ну если есть такая практика, может всё таки оставим её. Я просто не знал. Хотя вижу, что ты уже убрал...

2022-02-04 07:53 UTC, Kostelano commented on administrator/language/ru-RU/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_DESC="Включить или отключить функцию логирования событий, за&#160;исключением категории устаревшего API."
По админке много где используется неразрывный пробел. Скажем, на моем мониторе (он небольшой) перенос строки как раз после "за" - я это замечаю, ставлю неразрыв. Но мониторов куча, разрешений куча, все не отследишь и на 100% не исправишь. Не стршно :)

2022-02-06 10:42 UTC, Kostelano commented on administrator/language/ru-RU/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
Исправлено в https://github.com/JPathRu/localisation/pull/84/commits/ef6c3889fe7c24904a70fd5c2df9928d3145d9d4

2022-02-06 10:42 UTC, Kostelano commented on administrator/language/ru-RU/com_scheduler.sys.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Компонент для управления задачами."
Исправлено в https://github.com/JPathRu/localisation/pull/84/commits/ef6c3889fe7c24904a70fd5c2df9928d3145d9d4

2022-02-08 08:07 UTC, b2z commented
@Kostelano ты закончил, можно делать ревью?

2022-02-08 08:15 UTC, Kostelano commented
Да, все залил

2022-02-08 16:08 UTC, b2z approved these changes

2022-02-09 06:14 UTC, merged